jdbc:
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/ohim2065hardwaredb?user=root
  userName: root
  passWord: jk78hj12uigfeRr7832ismr7h
  poolSize: 5
spring.autoconfigure.exclude:
  - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
