spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update
spring.datasource:
  driver_class_name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/ohim2065hardwaredb?user=root
  username: root
  password: admin
